name: Cypress test

on: [push]

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        run: yarn install

      - name: Run E2E test
        run: yarn cypress run
      
